; ma E0
; mw 0201E09401
; mw 80C4101040

ORG 0x0
; test 1
TEST1_X: WORD 0xFFFF
TEST1_EXPECTED_RES: WORD 0x0
TEST1_EXPECTED_FLAGS: WORD 0x5 ; N = 0, Z = 1, V = 0, C = 1
TEST1_IS_CORRECT: WORD 0x0

; test 2
TEST2_X: WORD 0x0
TEST2_EXPECTED_RES: WORD 0x1
TEST2_EXPECTED_FLAGS: WORD 0x0 ; N = 0, Z = 0, V = 0, C = 0
TEST2_IS_CORRECT: WORD 0x0

; test 3
TEST3_X: WORD 0x7FFF
TEST3_EXPECTED_RES: WORD 0x8000
TEST3_EXPECTED_FLAGS: WORD 0xA ; N = 1, Z = 0, V = 1, C = 0
TEST3_IS_CORRECT: WORD 0x0

PS_FLAGS_MASK: WORD 0xF

ORG 0xD6
START:
    CALL $TEST1
    LD $TEST1_IS_CORRECT
    HLT

    CALL $TEST2
    LD $TEST2_IS_CORRECT
    HLT

    CALL $TEST3
    LD $TEST3_IS_CORRECT
    HLT
    

TEST1:
    WORD 0x9000 ; INC $TEST1_X
    PUSHF
    LD $TEST1_X
    CMP $TEST1_EXPECTED_RES
    BEQ TEST1_CMP_FLAGS
    
    TEST1_INCORRECT:
        CLA
        ST $TEST1_IS_CORRECT
        JUMP TEST1_RETURN

    TEST1_CMP_FLAGS:
        LD &0
        AND $PS_FLAGS_MASK
        CMP $TEST1_EXPECTED_FLAGS
        BNE TEST1_INCORRECT
        LD #1
        ST $TEST1_IS_CORRECT 

    TEST1_RETURN:
        POP
        RET

TEST2:
    WORD 0x9004 ; INC $TEST2_X
    PUSHF
    LD $TEST2_X
    CMP $TEST2_EXPECTED_RES
    BEQ TEST2_CMP_FLAGS
    
    TEST2_INCORRECT:
        CLA
        ST $TEST2_IS_CORRECT
        JUMP TEST2_RETURN

    TEST2_CMP_FLAGS:
        LD &0
        AND $PS_FLAGS_MASK
        CMP $TEST2_EXPECTED_FLAGS
        BNE TEST2_INCORRECT
        LD #1
        ST $TEST2_IS_CORRECT 

    TEST2_RETURN:
        POP
        RET

TEST3:
    WORD 0x9008 ; INC $TEST3_X
    PUSHF
    LD $TEST3_X
    CMP $TEST3_EXPECTED_RES
    BEQ TEST3_CMP_FLAGS
    
    TEST3_INCORRECT:
        CLA
        ST $TEST3_IS_CORRECT
        JUMP TEST3_RETURN

    TEST3_CMP_FLAGS:
        LD &0
        AND $PS_FLAGS_MASK
        CMP $TEST3_EXPECTED_FLAGS
        BNE TEST3_INCORRECT
        LD #1
        ST $TEST3_IS_CORRECT 

    TEST3_RETURN:
        POP
        RET
