DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS telescopes CASCADE;
DROP TABLE IF EXISTS shapes CASCADE;
DROP TABLE IF EXISTS components CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS maintenances CASCADE;